### ISSUE TITLE
AttributeError: 'Alphabet' object has no attribute 'stop_growth'

### ISSUE THREAD

**Issue by pandahop** [timvieira/crf#16] opened 2021-09-07 11:22 UTC
i ran this on repl.it after installing arsenal and crf package successfully.

```~/SorrowfulKnowledgeableOrigin/crf$ python crf/example.py test
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ykbg_s95 because the default path (/config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "crf/example.py", line 160, in <module>
    main()
  File "crf/example.py", line 154, in main
    run_test()
  File "crf/example.py", line 126, in run_test
    (L, A) = build_domain(train)
  File "/home/runner/SorrowfulKnowledgeableOrigin/crf/crf/stringcrf.py", line 20, in build_domain
    A.stop_growth()
AttributeError: 'Alphabet' object has no attribute 'stop_growth'```

**Comment by timvieira** [comment] 2021-09-07 16:42
Thanks for the error report.  I believe the issue is fixed now.  Please re-open the issue if that is not the case!

**Closed as completed by timvieira** 2021-09-07 16:42 UTC
